// tests/oracles/citations_resolve.mjs
//
// ⚠️ A DOCSTRING THAT NAMES A TEST WHICH DOES NOT EXIST IS WORSE THAN NO
// DOCSTRING. It tells the next reader the invariant is guarded, so they stop
// checking — and it tells a reader who DOES check that the guard was deleted,
// when in fact it was never written.
//
// Three of five citations in this tree were dangling when this was added:
//
//   frameClock.ts            → tests/oracles/frame_clock.mjs        (absent)
//   babylonSideEffects.ts    → tests/oracles/babylon_side_effects.mjs (absent,
//                              and its sentence was "fails the build if a
//                              module calls a patched API without it")
//   cameraGestures.ts        → tests/consistency/camera_gesture_test.ts (absent;
//                              five constants were exported for it)
//
// The babylonSideEffects one was the instructive case: the check DID exist, in
// scene_seam.mjs, under a name the docstring did not give. So the citation was
// not a lie about coverage — it was a wrong address, which is just as costly,
// because the next person writes the duplicate. (I did, most of the way.)
import { readFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";

const ROOT = new URL("../../", import.meta.url).pathname;
let fail = 0;
const eq = (name, got, want) => {
  const ok = JSON.stringify(got) === JSON.stringify(want);
  console.log(`    ${ok ? "PASS" : "FAIL"}  ${name}  →  ${JSON.stringify(got)}${ok ? "" : `  (wanted ${JSON.stringify(want)})`}`);
  if (!ok) fail++;
};

// ⚠️ WHERE A CITATION IS A PROMISE, AND WHERE IT IS NOT.
//
//  · src/, rootfs/, villa-kiosk/, .github/, vite.config.ts — a path named here
//    tells a maintainer "this rule is enforced". That is the promise to check.
//  · tests/ — an oracle NARRATING the defect it was written for must be able to
//    name the absent file by its old path. Three of the files here do exactly
//    that. Scanning them made the gate flag its own explanations.
//  · villa-kiosk-dev2/ — GENERATED by CI and never
//    hand-edited, so a stale citation in them is fixed by regenerating, not by
//    a person. Failing on it would block a release nobody can unblock.
const PROMISES = /^(?:src|rootfs|villa-kiosk|\.github)\/|^vite\.config\.ts$/;
const files = execFileSync("git", ["ls-files"], { encoding: "utf8", cwd: ROOT })
  .split("\n")
  .filter((f) => /\.(ts|tsx|py|mjs|sh|yaml|conf)$/.test(f))
  .filter((f) => PROMISES.test(f) && !/^villa-kiosk-dev2\//.test(f));
if (files.length < 50) { console.log(`    FAIL  the scan reached the promise-bearing tree  →  ${files.length}`); process.exit(1); }

// Every tests/… path mentioned anywhere in tracked source, with the trailing
// sentence punctuation stripped — "see tests/oracles/frame_clock.mjs." ends in
// a full stop that is prose, not filename.
const cited = new Map();
for (const f of files) {
  for (const m of readFileSync(ROOT + f, "utf8").matchAll(/tests\/[A-Za-z0-9_/.-]+/g)) {
    const path = m[0].replace(/[.,;:]+$/, "");
    if (!/\.[a-z]+$/.test(path)) continue;      // a directory, not a file
    if (!cited.has(path)) cited.set(path, []);
    if (!cited.get(path).includes(f)) cited.get(path).push(f);
  }
}
console.log(`  scanned ${files.length} tracked files, found ${cited.size} cited test paths\n`);
eq("the scan found citations at all", cited.size > 3, true);

console.log("  every test a source file names actually exists:");
const dangling = [...cited].filter(([p]) => !existsSync(ROOT + p))
  .map(([p, who]) => `${p} (cited by ${who.join(", ")})`);
for (const [p, who] of [...cited].sort()) {
  if (existsSync(ROOT + p)) console.log(`      ok  ${p}  ←  ${who.join(", ")}`);
}
eq("no citation dangles", dangling.length ? dangling : "none", "none");

console.log(`\n${fail ? `❌ ${fail} failed` : "✅ every cited test exists"}`);
process.exit(fail ? 1 : 0);
