// The Facility monthly document is the RECAP (owner, 2026-10-04: "rename
// 'report' in the UI … it can be confused with the report generated by the
// agent"). "Report" now means only what the VESTA Agent sends. The tab's
// screen is .tsx (pinned by text); the stored kind is driven by value.
import { register } from "node:module";
import { readFileSync } from "node:fs";
register("../consistency/alias-hook.mjs", import.meta.url);
import { ck, done } from "../consistency/check.mjs";
const { recapKind } = await import("@/fm/fmTypes");
const rd = (p) => readFileSync(new URL(`../../src/${p}`, import.meta.url), "utf8");
const code = (s) => s.split("\n").filter((l) => !/^\s*(\/\/|\/?\*)/.test(l)).join("\n");

const doc = { id: "1", month: "2026-09", markdown: "#", generatedAt: 0 };
ck("a recap saved before the rename (kind \"report\") reads as a recap",
   recapKind({ ...doc, kind: "report" }).kind === "recap");
ck("  ...and the other kinds pass untouched", recapKind({ ...doc, kind: "spend" }).kind === "spend"
   && recapKind({ ...doc, kind: "recap" }).kind === "recap");

const screens = ["components/fm/RecapTab.tsx", "components/fm/FacilitySections.tsx", "components/fm/SavedDocumentsList.tsx"];
const said = screens.filter((p) => /\breport\b/i.test(code(rd(p))));
ck("no Facility screen says 'report' for its own document", said.length === 0, said);
const builder = code(rd("fm/fmDocuments.ts"));
ck("the recap's own title and sections say 'recap'",
   /"operations recap"/.test(builder) && !/report date/.test(builder));
done("✅ the Facility document is the recap; 'report' is the Agent's word");
